### ISSUE TITLE
I Hear Nothing!

### ISSUE THREAD

**Issue by KhunRoger** [TommyMaes/SetVol#1]
I hear no sound during the installation, or Menu Item 4 "Enable Startup", or Menu Item 1 "Configure Volume", or Menu Item 2 "Test Volume".

However, the volume level is correctly set and gets correctly reset (if I manually change it) after startup.

I haven't worked out which piece of code in your files is supposed to produce any sound. Perhaps you can say and I'll investigate.

Apart from that, it works!

**Comment by TommyMaes** [comment]
During installation and enabling startup there should be no mention of anything like that. Could be you have an older version which has a bug (discovered some bugs lately but kept the version 5.1 name without realizing)

During configuring, If I’m not mistaken, the program says something like; you should now hear the desired volume. It doesn’t say that you hear an audio sample or anything like that. But i understand the confusion this gives. 
There is no audio feedback function at this moment.

Maybe I should give feedback something like; your master volume is now set to the desired volume. 
Or I could include a sample sound which is a (accidental) great idea from your part.

Will look into it.

Thank you for your feedback!

TommyMaes

**Comment by TommyMaes** [comment]
Fixed the issue

Plaese try the latest verison:
[SetVol 5.2 by TommyMaes](https://github.com/TommyMaes/SetVol/raw/main/SetVol%205.2%20by%20TommyMaes.zip)

**Comment by KhunRoger** [comment]
Thanks, Tommy!
